spring:
    profiles:
        include:
            - redis
# Actuator
management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
            base-path: /actuator
        jmx:
            exposure:
                exclude: "*"
    endpoint:
        health:
            show-details: never
    individual:
        health: