spring:
    profiles:
        include:
            - redis
            - datasource

# Actuator
management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
            base-path: /actuator
        jmx:
            exposure:
                exclude: "*"
    endpoint:
        health:
            show-details: never
    individual:
        health:
            
#Payment
vnpay:
    tmn-code: YOUR_TMN_CODE
    hash-secret: YOUR_HASH_SECRET
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/payment/vnpay-return