#!/bin/sh

echo "Running Spotless on staged files..."

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".java$")

if [ -z "$FILES" ]; then
  exit 0
fi

./gradlew spotlessApply

git add $FILES